version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - redis_data:/data

  celery:
    build: ../backend
    command: celery -A PhyHub worker -B
#    volumes:
#      - ./project:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  backend:
    build: ../backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - postgres
    env_file:
      - .env

  nginx:
    image: nginx:1.25.1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
