# Generated by Django 4.2.4 on 2023-08-30 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Наименование')),
                ('parameter', models.CharField(max_length=20, verbose_name='Параметр')),
                ('type', models.CharField(choices=[('abs', 'Абсолютное значение'), ('rel', 'Относительное значение')], max_length=5, verbose_name='Тип параметра')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включен')),
                ('description', models.CharField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сенсор',
                'verbose_name_plural': 'Сенсоры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Наименование')),
                ('url', models.URLField(verbose_name='url')),
                ('periodicity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Периодичность опроса, сек.')),
                ('description', models.CharField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Сенсор')),
            ],
            options={
                'verbose_name': 'Показание сенсора',
                'verbose_name_plural': 'Показания сенсоров',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensors.sensorendpoint', verbose_name='Endpoint'),
        ),
    ]
