# Generated by Django 4.2.4 on 2023-10-23 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Полное наименование')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='Slug')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включен')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сенсор',
                'verbose_name_plural': 'Сенсоры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('start_value_range', models.FloatField(verbose_name='Значение с')),
                ('stop_value_range', models.FloatField(verbose_name='Значение до')),
                ('need_comment', models.BooleanField(verbose_name='Необходим комментарий оператора')),
                ('color', models.CharField(help_text='html цвет, например #4285f4', max_length=7, verbose_name='Цвет')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='sensors.sensor', verbose_name='Сенсор')),
            ],
            options={
                'verbose_name': 'Состояние сенсора',
                'verbose_name_plural': 'Состояния сенсоров',
            },
        ),
        migrations.CreateModel(
            name='WorkingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='С')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='До')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_intervals', to='sensors.sensor', verbose_name='Сенсор')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensorstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рабочий интервал',
                'verbose_name_plural': 'Рабочие интервалы',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время измерения')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Сенсор')),
                ('working_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.workinginterval', verbose_name='Измерения')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
                'ordering': ['measured_at'],
            },
        ),
    ]
