# Generated by Django 4.2.4 on 2023-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='slug',
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.SlugField(default='ss', max_length=25, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='verbose_name',
            field=models.CharField(max_length=50, verbose_name='Полное наименование'),
        ),
    ]
