# Generated by Django 4.2.4 on 2023-11-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sensorstatus',
            name='need_comment',
            field=models.BooleanField(verbose_name='Необходим комментарий'),
        ),
        migrations.CreateModel(
            name='StatusReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='Причина состояния')),
                ('priority', models.PositiveSmallIntegerField(default=32767, verbose_name='Приоритет')),
                ('sensor_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='sensors.sensorstatus', verbose_name='Состояние сенсора')),
            ],
            options={
                'verbose_name': 'Причина состояния',
                'verbose_name_plural': 'Причины состояний',
            },
        ),
    ]
