# Generated by Django 4.2.4 on 2023-09-15 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('scl', 'Абсолютное значение'), ('cnt', 'Накопительное значение')], max_length=3, verbose_name='Тип параметра'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='measured_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время измерения'),
        ),
    ]
