# Generated by Django 4.2.4 on 2023-10-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='working_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.workinginterval', verbose_name='Измерения'),
        ),
    ]
