# Generated by Django 4.2.4 on 2023-08-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorendpoint',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Включен'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Имя'),
        ),
    ]
