# Generated by Django 4.2.4 on 2023-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensor_slug_sensor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.SlugField(max_length=25, unique=True, verbose_name='Имя'),
        ),
    ]
