# Generated by Django 4.2.4 on 2023-11-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensorstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusreason',
            options={'ordering': ['group', 'priority', 'reason'], 'verbose_name': 'Причина состояния', 'verbose_name_plural': 'Причины состояний'},
        ),
        migrations.AddField(
            model_name='statusreason',
            name='group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Группа'),
        ),
    ]
