# Generated by Django 4.2.4 on 2023-10-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensor_name_alter_sensorreading_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idl', 'Простой'), ('run', 'Работа')], max_length=3, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='С')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='До')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_intervals', to='sensors.sensor', verbose_name='Сенсор')),
            ],
            options={
                'verbose_name': 'Рабочий интервал',
                'verbose_name_plural': 'Рабочие интервалы',
            },
        ),
    ]
