# Generated by Django 4.2.4 on 2023-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_rename_start_value_range_sensorstatus_value_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinginterval',
            name='last_reading_value',
            field=models.FloatField(default=0, verbose_name='Крайнее измеренное значение'),
        ),
    ]
