name: PhyHub workflow
on: [ push ]
jobs:

  build_and_push_backend_to_docker_hub:
    if: ${{ github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: kraleksey/phyhub:latest

  send_message:
    if: ${{ always() }}
    needs: [ build_and_push_backend_to_docker_hub ]
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }}
            Actor: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Results:
              building and pushing back: ${{ needs.build_and_push_backend_to_docker_hub.result }}
